[genai]
GEMINI_API_KEY = "AIzaSyC46i8Dq-YHfh_Ah8CvV7Hk-s-TGlzCd50"

[openai]
OPENAI_API_KEY = " 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"

[grok]
GROK_API_KEY = "xai-8z2OWSAl4Oqc1B6J0oNynxR0ONDbLk0yoMQot9Acw8h2XHLYbGelBm49tqs0KrX38Zn65WynUCQtGhj1"
