services:
  homework8-soar-app:
    build: .
    container_name: homework8-soar
    ports:
      - "9001:8501"  # Map host port 9001 to the application's port 8501 inside the container
    volumes:
      # Mount the entire project directory for instant code changes
      - .:/app
    # CORRECTED COMMAND: Points to app.py in the root of the /app directory
    command: /bin/sh -c "python /app/updated_app/updated_train_model.py && streamlit run /app/updated_app/updated_app.py --server.fileWatcherType none"
